# Generated by Django 4.2.2 on 2023-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromodel',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portada', verbose_name='Foto de Portada'),
        ),
        migrations.AlterField(
            model_name='libromodel',
            name='visitas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
