# Generated by Django 4.2.2 on 2023-06-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromodel',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
