# Generated by Django 4.2.2 on 2023-06-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_libromodel_portada_alter_libromodel_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromodel',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_libro', to='libro.categoriamodel'),
        ),
    ]
