# Generated by Django 4.2.2 on 2023-06-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad')),
                ('edad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MODELNAME',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
        migrations.CreateModel(
            name='PrestamoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prstamo', models.DateField(verbose_name='Retiro el Libro')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Devolvio el Libro')),
                ('devuelto', models.BooleanField()),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='lector.lectormodel')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.libromodel')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
