# Generated by Django 4.2.2 on 2023-06-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectormodel',
            options={'verbose_name': 'Lector ', 'verbose_name_plural': 'Lectores'},
        ),
    ]
