# Generated by Django 4.2.2 on 2023-06-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamomodel_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamomodel',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo', to='lector.lectormodel'),
        ),
    ]
