# Generated by Django 4.2.2 on 2023-06-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libromodel_categoria'),
        ('lector', '0003_alter_prestamomodel_lector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamomodel',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.libromodel'),
        ),
    ]
